name: wizards_staff
channels:
  - conda-forge
  - bioconda

dependencies:
  - python=3.11.9
  - pip=24.0
  - bokeh=3.4.2
  - opencv=4.8.1
  - holoviews=1.19.0
  - ipython=8.25.0
  - matplotlib=3.8.4
  - numpy=1.26.4
  - psutil=6.0.0
  - scikit-image=0.24.0
  - tifffile=2024.6.18
  - xmltodict=0.13.0
  - tqdm=4.66.4
  - scipy=1.10.1
  - h5py=3.11.0
  - pims=0.7
  - ipywidgets=8.1.3
  - scikit-learn=1.5.0
  - zarr=2.18.2
  - pynwb=2.8.0
  - ipyparallel=8.8.0
  - tensorflow=2.15.0
  - peakutils=1.3.5
  - caiman=1.11.3
  - pip:
    - aicspylibczi==3.1.2
    - glob2
    - pprintpp